printf "\n-------------------\n" && curl -sw '\nResponse Status : %{http_code}' --location --request PUT 'localhost:8080/pdas/1' --header 'Content-Type: application/json' --data-binary "@./sample/samplePDA-1.json"
printf "\n-------------------\n" && curl -sw '\nResponse Status : %{http_code}' --location --request GET 'localhost:8080/pdas'
printf "\n-------------------\n" && curl -sw '\nResponse Status : %{http_code}' --location --request PUT 'localhost:8080/pdas/1/reset' --data-raw ''
printf "\n-------------------\n" && curl -sw '\nResponse Status : %{http_code}' --location --request PUT 'localhost:8080/pdas/1/tokens/0' --header 'Content-Type: application/json' --data-raw '0'
printf "\n-------------------\n" && curl -sw '\nResponse Status : %{http_code}' --location --request PUT 'localhost:8080/pdas/1/tokens/1' --header 'Content-Type: application/json' --data-raw '0'
printf "\n-------------------\n" && curl -sw '\nResponse Status : %{http_code}' --location --request PUT 'localhost:8080/pdas/1/tokens/2' --header 'Content-Type: application/json' --data-raw '1'
printf "\n-------------------\n" && curl -sw '\nResponse Status : %{http_code}' --location --request PUT 'localhost:8080/pdas/1/tokens/3' --header 'Content-Type: application/json' --data-raw '1'
printf "\n-------------------\n" && curl -sw '\nResponse Status : %{http_code}' --location --request PUT 'localhost:8080/pdas/1/eos/4' --data-raw ''
printf "\n-------------------\n" && curl -sw '\nResponse Status : %{http_code}' --location --request GET 'localhost:8080/pdas/1/is_accepted'
printf "\n-------------------\n" && curl -sw '\nResponse Status : %{http_code}' --location --request GET 'localhost:8080/pdas/1/stack/top/2'
printf "\n-------------------\n" && curl -sw '\nResponse Status : %{http_code}' --location --request GET 'localhost:8080/pdas/1/stack/len'
printf "\n-------------------\n" && curl -sw '\nResponse Status : %{http_code}' --location --request GET 'localhost:8080/pdas/1/state'
printf "\n-------------------\n" && curl -sw '\nResponse Status : %{http_code}' --location --request GET 'localhost:8080/pdas/1/tokens'
printf "\n-------------------\n" && curl -sw '\nResponse Status : %{http_code}' --location --request GET 'localhost:8080/pdas/1/snapshot/2'
printf "\n-------------------\n" && curl -sw '\nResponse Status : %{http_code}' --location --request PUT 'localhost:8080/pdas/1/close' --data-raw ''
printf "\n-------------------\n" && curl -sw '\nResponse Status : %{http_code}' --location --request DELETE 'localhost:8080/pdas/1/delete' --data-raw ''